In [14]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

In [15]:
df = pd.read_csv('feature_time_final.csv')

In [16]:
train_data, test_data = train_test_split(df, test_size = 750, stratify = df['fault'],
                                         random_state = 1288)

In [17]:
train_data

Unnamed: 0       Max       Min      Mean    Stddev       RMS      skew  \
3647        3647  3.538987 -3.921264  0.014476  0.666431  0.666263 -0.560687   
1283        1283  0.383852 -0.390111  0.010527  0.147372  0.147675 -0.021402   
1862        1862  0.703242 -0.497339  0.031091  0.172658  0.175352  0.324523   
349          349  0.506727 -0.470636  0.017011  0.165334  0.166126  0.057158   
2903        2903  4.687071 -4.730891  0.011463  1.119911  1.119423  0.031470   
...          ...       ...       ...       ...       ...       ...       ...   
1035        1035  0.438510 -0.447689  0.012249  0.148248  0.148681  0.038450   
1673        1673  1.559609 -1.312191  0.018975  0.304190  0.304633  0.097104   
1304        1304  0.487326 -0.490038  0.010448  0.191598  0.191789  0.050280   
3524        3524  0.345258 -0.400542  0.006340  0.142669  0.142741 -0.090789   
2911        2911  4.151632 -4.038535  0.003886  1.004651  1.004168  0.040179   

       kurtosis  crest_factor  form_factor  fault  
3647  10.016598      5.311699    46.024533  OR021  
1283  -0.411388      2.599301    14.028601   B021  
1862   0.869200      4.010467     5.639985  IR014  
349    0.044447      3.050252     9.765626   B007  
2903   2.969016      4.187041    97.653493  OR007  
...         ...           ...          ...    ...  
1035  -0.121018      2.949340    12.137753   B021  
1673   4.081576      5.119636    16.054568  IR007  
1304  -0.653760      2.540942    18.355695   B021  
3524  -0.434324      2.418783    22.513011  OR014  
2911   2.828750      4.134402   258.405858  OR007  

[3801 rows x 11 columns]

In [18]:
X_train=train_data.iloc[:,:-1]
y_train=train_data.iloc[:,-1]

In [19]:
X_train

Unnamed: 0       Max       Min      Mean    Stddev       RMS      skew  \
3647        3647  3.538987 -3.921264  0.014476  0.666431  0.666263 -0.560687   
1283        1283  0.383852 -0.390111  0.010527  0.147372  0.147675 -0.021402   
1862        1862  0.703242 -0.497339  0.031091  0.172658  0.175352  0.324523   
349          349  0.506727 -0.470636  0.017011  0.165334  0.166126  0.057158   
2903        2903  4.687071 -4.730891  0.011463  1.119911  1.119423  0.031470   
...          ...       ...       ...       ...       ...       ...       ...   
1035        1035  0.438510 -0.447689  0.012249  0.148248  0.148681  0.038450   
1673        1673  1.559609 -1.312191  0.018975  0.304190  0.304633  0.097104   
1304        1304  0.487326 -0.490038  0.010448  0.191598  0.191789  0.050280   
3524        3524  0.345258 -0.400542  0.006340  0.142669  0.142741 -0.090789   
2911        2911  4.151632 -4.038535  0.003886  1.004651  1.004168  0.040179   

       kurtosis  crest_factor  form_factor  
3647  10.016598      5.311699    46.024533  
1283  -0.411388      2.599301    14.028601  
1862   0.869200      4.010467     5.639985  
349    0.044447      3.050252     9.765626  
2903   2.969016      4.187041    97.653493  
...         ...           ...          ...  
1035  -0.121018      2.949340    12.137753  
1673   4.081576      5.119636    16.054568  
1304  -0.653760      2.540942    18.355695  
3524  -0.434324      2.418783    22.513011  
2911   2.828750      4.134402   258.405858  

[3801 rows x 10 columns]

In [20]:
y_train

3647    OR021
1283     B021
1862    IR014
349      B007
2903    OR007
        ...  
1035     B021
1673    IR007
1304     B021
3524    OR014
2911    OR007
Name: fault, Length: 3801, dtype: object

In [21]:
test_data

Unnamed: 0       Max       Min      Mean    Stddev       RMS      skew  \
1236        1236  0.536142 -0.542817  0.009619  0.169993  0.170182 -0.008303   
2458        2458  2.478977 -2.064249  0.012574  0.657331  0.657130  0.036444   
2037        2037  0.805464 -0.921454  0.029354  0.215751  0.217634 -0.116876   
2386        2386  2.286633 -1.985810  0.010057  0.564010  0.563824  0.046207   
3586        3586  0.414102 -0.473974  0.009695  0.147196  0.147444 -0.251901   
...          ...       ...       ...       ...       ...       ...       ...   
2572        2572  2.407004 -2.446850  0.015207  0.723924  0.723730  0.045434   
2138        2138  0.651089 -0.731823  0.028575  0.199007  0.200952 -0.207212   
52            52  0.332950 -0.342546  0.017227  0.119245  0.120425 -0.059051   
834          834  0.393866 -0.312923  0.006617  0.112715  0.112855  0.161175   
1374        1374  1.301969 -1.051213  0.024714  0.289470  0.290382  0.168430   

      kurtosis  crest_factor  form_factor  fault  
1236  0.669727      3.150399    17.692057   B021  
2458  0.855251      3.772430    52.259451  IR021  
2037  1.135915      3.701006     7.414147  IR014  
2386  1.018262      4.055581    56.060928  IR021  
3586  0.391675      2.808541    15.208356  OR014  
...        ...           ...          ...    ...  
2572  0.768867      3.325832    47.593417  IR021  
2138  0.318896      3.240026     7.032477  IR014  
52   -0.001503      2.764785     6.990555   B007  
834   0.036898      3.490032    17.056238   B014  
1374  3.162693      4.483645    11.749784  IR007  

[750 rows x 11 columns]

In [22]:
X_test=test_data.iloc[:,:-1]
y_test=test_data.iloc[:,-1]

### Model building

In [23]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

C:\ProgramData\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[22:00:53] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[74  1  0  0  0  0  0  0  0  0]
 [ 0 75  0  0  0  0  0  0  0  0]
 [ 0  0 73  0  0  0  0  0  0  0]
 [ 0  0  0 76  0  0  0  0  0  0]
 [ 0  0  0  0 75  0  0  0  0  0]
 [ 0  0  0  0  0 74  0  1  0  0]
 [ 0  0  0  0  0  0 75  0  0  0]
 [ 0  0  0  0  0  0  0 75  0  0]
 [ 0  0  0  0  0  0  0  0 75  0]
 [ 0  0  0  0  0  0  0  0  0 76]]


0.9973333333333333

In [25]:
from sklearn import metrics



# Print the confusion matrix
print(metrics.confusion_matrix(y_test, y_pred))

# Print the precision and recall, among other metrics
print(metrics.classification_report(y_test, y_pred, digits=3))

[[74  1  0  0  0  0  0  0  0  0]
 [ 0 75  0  0  0  0  0  0  0  0]
 [ 0  0 73  0  0  0  0  0  0  0]
 [ 0  0  0 76  0  0  0  0  0  0]
 [ 0  0  0  0 75  0  0  0  0  0]
 [ 0  0  0  0  0 74  0  1  0  0]
 [ 0  0  0  0  0  0 75  0  0  0]
 [ 0  0  0  0  0  0  0 75  0  0]
 [ 0  0  0  0  0  0  0  0 75  0]
 [ 0  0  0  0  0  0  0  0  0 76]]
              precision    recall  f1-score   support

        B007      1.000     0.987     0.993        75
        B014      0.987     1.000     0.993        75
        B021      1.000     1.000     1.000        73
       IR007      1.000     1.000     1.000        76
       IR014      1.000     1.000     1.000        75
       IR021      1.000     0.987     0.993        75
      Normal      1.000     1.000     1.000        75
       OR007      0.987     1.000     0.993        75
       OR014      1.000     1.000     1.000        75
       OR021      1.000     1.000     1.000        76

    accuracy                          0.997       750
   macro avg      0